import 'package:flutter/material.dart';
import 'package:quizzler/quiz.dart';
import 'package:rflutter_alert/rflutter_alert.dart';

Quiz quiz = Quiz();
void main() => runApp(Quizzler());

class Quizzler extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.grey.shade900,
        body: Padding(
          padding: EdgeInsets.symmetric(horizontal: 10.0),
          child: QuizPage(),
        ),
      ),
    );
  }
}

class QuizPage extends StatefulWidget {
  @override
  _QuizPageState createState() => _QuizPageState();
}

class _QuizPageState extends State<QuizPage> {
  List<Icon> scoreKeeper = [];
  void checkAnswer(bool userPickAnswer) {
    bool correctAnswer = quiz.getQuestionAnswer();
    setState(() {
      if (quiz.isFinished() == true) {
        Alert(
          context: context,
          title: 'Finish',
          desc: 'you have completed successfully',
        ).show();
        quiz.reset();
      } else if (userPickAnswer == correctAnswer) {
        scoreKeeper.add(Icon(
          Icons.check,
          color: Colors.green,
        ));
      } else {
        scoreKeeper.add(Icon(
          Icons.close,
          color: Colors.red,
        ));
      }

      quiz.nextQuestion();
    });
  }

  // List<String> questions = [
  //   'Is DGPC App Development Company?.',
  //   'Approximately one quarter Bhutan\'s revenue is generated by DGPC?.',
  //   'A DGPC\'s logo is green?.',
  // ];

  // List<bool> answer = [
  //   false,
  //   true,
  //   true,
  // ];

  // Question q1 = Question(q: 'Is DGPC App Development Company?.', a: false);

  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: <Widget>[
        Expanded(
          flex: 5,
          child: Padding(
            padding: EdgeInsets.all(10.0),
            child: Center(
              child: Text(
                quiz.getqustiontext(),
                textAlign: TextAlign.center,
                style: TextStyle(
                  fontSize: 25.0,
                  color: Colors.white,
                ),
              ),
            ),
          ),
        ),
        Expanded(
          child: Padding(
            padding: EdgeInsets.all(15.0),
            child: TextButton(
              style: ButtonStyle(
                backgroundColor: MaterialStateProperty.all<Color>(Colors.green),
              ),
              child: Text(
                'True',
                style: TextStyle(
                  fontSize: 20.0,
                  color: Colors.white,
                ),
              ),
              onPressed: () {
                checkAnswer(true);
                //The user picked true.
              },
            ),
          ),
        ),
        Expanded(
          child: Padding(
            padding: EdgeInsets.all(15.0),
            child: TextButton(
              style: ButtonStyle(
                backgroundColor: MaterialStateProperty.all<Color>(Colors.red),
              ),
              child: Text(
                'False',
                style: TextStyle(
                  fontSize: 20.0,
                  color: Colors.white,
                ),
              ),
              onPressed: () {
                // //The user picked true.
                // bool correctAnswer = quiz.getQuestionAnswer();
                // if (correctAnswer == true) {
                //   print('User got it right!');
                // } else {
                //   print('User got it Wrong!');
                // }
                // setState(() {
                //   quiz.nextQuestion();
                // });
                checkAnswer(false);
              },
            ),
          ),
        ),
        Row(
          children: scoreKeeper,
        )
      ],
    );
  }
}


/*
question1: 'Is DGPC App Development Company?.', false,
question2: 'Approximately one quarter Bhutan\'s revenue is generated by DGPC?.', true,
question3: 'A DGPC\'s logo is green.', true,
*/
